/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Modelo.FavoritosJDBC;
import Modelo.ClsConexion;
import Modelo.UsuarioJDBC;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Caleb
 */
public class FiltrosReport extends javax.swing.JFrame {

    /**
     * Creates new form FiltrosReport
     */
    private final DefaultTableModel modelo;
    private final BufferedImage buffer1 = null;
    private final Image imagen1 = null;
    private int contador = 0;
    private ResultSet resultadoConsulta;
    private String columna = "";
    private String valor = "";
    private String USER = "Caleb";
    
    public FiltrosReport() {
        initComponents();     
        modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("name");
        modelo.addColumn("generation_id");
        modelo.addColumn("height");
        modelo.addColumn("weight");
        modelo.addColumn("species");
        modelo.addColumn("capture_rate");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1Mail = new javax.swing.JButton();
        jButtonPDF = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboCOLORFIL = new javax.swing.JComboBox<>();
        txtRC = new javax.swing.JTextField();
        cboHABITADFILL = new javax.swing.JComboBox<>();
        txtEB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonFC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1FE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1Back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jButton1Mail.setBackground(new java.awt.Color(51, 51, 51));
        jButton1Mail.setForeground(new java.awt.Color(204, 204, 204));
        jButton1Mail.setText("Envio de correo");
        jButton1Mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1MailActionPerformed(evt);
            }
        });

        jButtonPDF.setBackground(new java.awt.Color(51, 51, 51));
        jButtonPDF.setForeground(new java.awt.Color(204, 204, 204));
        jButtonPDF.setText("Crear PDF");
        jButtonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel5.setText("Filtros pokedex");

        cboCOLORFIL.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboCOLORFIL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar opción", "red", "green", "white", "brown", "yellow", "purple", "blue", "pink", "gray", "black" }));
        cboCOLORFIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCOLORFILActionPerformed(evt);
            }
        });

        txtRC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cboHABITADFILL.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboHABITADFILL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar opción", "grassland", "mountain", "forest", "rough terrain", "cave", "urban", "sea", "rare" }));
        cboHABITADFILL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHABITADFILLActionPerformed(evt);
            }
        });

        txtEB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setText("Color:");

        jButtonFC.setBackground(new java.awt.Color(51, 51, 51));
        jButtonFC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonFC.setForeground(new java.awt.Color(204, 204, 204));
        jButtonFC.setText("ENTER");
        jButtonFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFCActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setText("Habitad");

        jButton1FE.setBackground(new java.awt.Color(51, 51, 51));
        jButton1FE.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1FE.setForeground(new java.awt.Color(204, 204, 204));
        jButton1FE.setText("ENTER");
        jButton1FE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1FEActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setText("Experiencia Base:");

        jButton1Back.setText("Regresar");
        jButton1Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BackActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setText("no. tasa de captura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1Mail)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(cboCOLORFIL, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(104, 104, 104)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEB, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboHABITADFILL, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRC, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(341, 341, 341))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonFC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1FE)
                        .addGap(138, 138, 138))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Back)
                    .addComponent(jButton1Mail)
                    .addComponent(jButtonPDF))
                .addGap(55, 55, 55)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboHABITADFILL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCOLORFIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonFC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1FE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1MailActionPerformed
        try {
            generarPDFreport(columna, valor);
            String destinatario = UsuarioJDBC.selectCorreo(USER);
            String tipoFiltro = columna.substring(0,1).toUpperCase() + columna.substring(1).toLowerCase();
            String path = "D:\\Caleb\\Documents\\PFreportes\\PokeReporte" + tipoFiltro + ".pdf";
            SendMail(destinatario, path);
            File reporte = new File(path);
            reporte.delete();
            JOptionPane.showMessageDialog(null,"El correo a sido enviado.");
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Error...");
        }
    }//GEN-LAST:event_jButton1MailActionPerformed

    private void jButtonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFActionPerformed
        try {
            generarPDFreport(columna, valor);
            JOptionPane.showMessageDialog(null, "Tu reporte ha sido guardado tu carpeta Documentos como un archivo pdf");
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Error.");
        }

    }//GEN-LAST:event_jButtonPDFActionPerformed

    private void cboCOLORFILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCOLORFILActionPerformed
        columna = "color";
        valor = cboCOLORFIL.getSelectedItem().toString();
        fillData(columna, valor);
        cboCOLORFIL.setSelectedIndex(0);
    }//GEN-LAST:event_cboCOLORFILActionPerformed

    private void cboHABITADFILLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHABITADFILLActionPerformed
        columna = "habitat";
        valor = cboHABITADFILL.getSelectedItem().toString();
        fillData(columna, valor);
        cboHABITADFILL.setSelectedIndex(0);
    }//GEN-LAST:event_cboHABITADFILLActionPerformed

    private void jButton1FEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1FEActionPerformed
        columna = "base_experience";
        valor = txtEB.getText();
        fillData(columna, valor);
        txtEB.setText("");
    }//GEN-LAST:event_jButton1FEActionPerformed

    private void jButton1BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BackActionPerformed
        VentanaPokedex ventanaPoke = new VentanaPokedex();
        ventanaPoke.setUSER(USER);
        ventanaPoke.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1BackActionPerformed

    private void jButtonFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFCActionPerformed
        columna = "capture_rate";
        valor = txtRC.getText();
        fillData(columna, valor);
        txtRC.setText("");
    }//GEN-LAST:event_jButtonFCActionPerformed

    public void setUSER(String usuario) {
        this.USER = usuario;
    }
    
    //Esto era para llenar tan]bla en esta  zona
    private void llenarTabla(String consul){    
        String tabla = "pokemon";
        try {
            resultadoConsulta = FavoritosJDBC.ejecutarConsulta(tabla, consul);
            String []info = new String[7];
            while (resultadoConsulta.next()){
                info[0] = resultadoConsulta.getString(1);
                info[1] = resultadoConsulta.getString(2);
                info[2] = resultadoConsulta.getString(5);
                info[3] = resultadoConsulta.getString(10);
                info[4] = resultadoConsulta.getString(11);
                info[5] = resultadoConsulta.getString(12);
                info[6] = resultadoConsulta.getString(17);
                modelo.addRow(info);
            } 
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }
    
    private void fillData(String columna, String valor) {
        if (!Objects.equals(valor, "Seleccionar opción")) {
            while (modelo.getRowCount() > 0) {
                modelo.removeRow(0);
            }
            llenarTabla("WHERE " + columna + " = '" + valor + "'");
        }
    }
    
    private void generarPDFreport(String columna, String valor){
        JasperReport jasperReport;
        JasperPrint jasperPrint; 
        Map parametros = null;
        try
        {
            if (!Objects.equals(columna, "") && !Objects.equals(valor, "")) {
                parametros = new HashMap();
                parametros.put("columna", columna);
                parametros.put("valor", valor);
            }
            String path = "D:\\Caleb\\Documents\\NetBeansProjects\\PokedexPF\\src\\main\\java\\Reportes\\PokeReporte.jasper";
            jasperReport = (JasperReport) JRLoader.loadObjectFromFile(path);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, ClsConexion.getConnection());
            JasperExportManager.exportReportToPdfFile( jasperPrint, "D:\\Caleb\\Documents\\PFreportes\\PokeReporte" + (columna.substring(0,1).toUpperCase() + columna.substring(1).toLowerCase()) + ".pdf");
        }
        catch (JRException ex) {
          System.err.println( "Error iReport: " + ex.getMessage());
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }
    //codigo de envio de correo
    private void SendMail(String destino, String path) {
        try {
            Properties props = new Properties();
            props.setProperty("mail.smtp.host", "smtp.gmail.com");
            props.setProperty("mail.smtp.starttls.enable", "true");
            props.setProperty("mail.smtp.port", "587");
            props.setProperty("mail.smtp.auth", "true");
            
            Session session = Session.getDefaultInstance(props);
            
            String correoRemitente = "kleb.2002.jm@@gmail.com";
            String passwordRemitente = "molmor1504";
            String correoReceptor = destino;
            
            String asunto = "Reporte Pokemon";
            
            BodyPart adjunto = new MimeBodyPart();
            adjunto.setDataHandler(new DataHandler(new FileDataSource(path)));
            adjunto.setFileName("Reporte.pdf");
            
            MimeMultipart multiparte = new MimeMultipart();
            multiparte.addBodyPart(adjunto);
            
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(correoRemitente));

            message.addRecipient(Message.RecipientType.TO, new InternetAddress(correoReceptor));
            message.setSubject(asunto);
            message.setContent(multiparte);
            
            Transport t = session.getTransport("smtp");
            t.connect(correoRemitente,passwordRemitente);
            t.sendMessage(message, message.getRecipients(Message.RecipientType.TO));
            t.close();
        } catch (AddressException ex) {
            ex.printStackTrace(System.out);
        } catch (MessagingException ex) {
            ex.printStackTrace(System.out);
        }                                         
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCOLORFIL;
    private javax.swing.JComboBox<String> cboHABITADFILL;
    private javax.swing.JButton jButton1Back;
    private javax.swing.JButton jButton1FE;
    private javax.swing.JButton jButton1Mail;
    private javax.swing.JButton jButtonFC;
    private javax.swing.JButton jButtonPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtEB;
    private javax.swing.JTextField txtRC;
    // End of variables declaration//GEN-END:variables
}
